# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-08 03:37
from __future__ import unicode_literals

import app.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('professional', 'Professional'), ('private', 'Private'), ('other', 'Education & Other')], max_length=10, verbose_name='타입')),
                ('start_date', models.DateTimeField(verbose_name='시작일')),
                ('end_date', models.DateTimeField(verbose_name='종료일')),
                ('company', models.CharField(max_length=255, verbose_name='회사')),
                ('company_link_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='회사 link')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='생성일')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
        ),
        migrations.CreateModel(
            name='ExperienceItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_str', models.CharField(max_length=255, verbose_name='Key')),
                ('value_str', models.CharField(blank=True, max_length=255, null=True, verbose_name='Value')),
                ('value_link_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='Value link')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='생성일')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.ExperienceItem')),
            ],
        ),
        migrations.CreateModel(
            name='Today',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='타이틀')),
                ('title_en', models.CharField(max_length=255, verbose_name='타이틀(EN)')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화여부')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='생성일')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
        ),
        migrations.CreateModel(
            name='TodayItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_str', models.CharField(max_length=255, verbose_name='Key')),
                ('value_str', models.CharField(blank=True, max_length=255, null=True, verbose_name='Value')),
                ('value_link_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='Value link')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='생성일')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('today', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Today')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=320, unique=True, verbose_name='유저명')),
                ('username_en', models.CharField(max_length=320, unique=True, verbose_name='유저명(EN)')),
                ('intro', models.TextField(blank=True, null=True, verbose_name='소개')),
                ('intro_en', models.TextField(blank=True, null=True, verbose_name='소개(EN)')),
                ('email', models.EmailField(blank=True, max_length=320, null=True, verbose_name='이메일')),
                ('facebook_id', models.CharField(blank=True, max_length=255, null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to=app.models.profile_upload_path)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='가입일')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
