# Generated by Django 2.1 on 2021-01-05 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_kr', models.CharField(max_length=100, verbose_name='목표명(한글)')),
                ('title_en', models.CharField(max_length=100, verbose_name='목표명(영어)')),
                ('goal_status_kr', models.TextField(verbose_name='목표 상태(한글)')),
                ('goal_status_en', models.TextField(verbose_name='목표 상태(영어)')),
                ('curr_status_kr', models.TextField(verbose_name='현재 상태(한글)')),
                ('curr_status_en', models.TextField(verbose_name='현재 상태(영어)')),
                ('goal_point', models.PositiveIntegerField(verbose_name='목표 포인트')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='노출 순서')),
                ('crt_dt', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='GoalTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_kr', models.CharField(max_length=100, verbose_name='과제명(한글)')),
                ('title_en', models.CharField(max_length=100, verbose_name='과제명(영어)')),
                ('task_dt', models.DateField(verbose_name='과제수행일')),
                ('task_point', models.PositiveIntegerField(verbose_name='과제 포인트')),
                ('remembered_years', models.PositiveIntegerField(default=10, verbose_name='기억기간(years)')),
                ('link_url', models.URLField(blank=True, null=True, verbose_name='관련 링크')),
                ('crt_dt', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Goal')),
            ],
            options={
                'ordering': ['-task_dt', '-id'],
            },
        ),
    ]
