# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-08 03:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username_en',
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='이름'),
        ),
        migrations.AddField(
            model_name='user',
            name='name_en',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='이름(EN)'),
        ),
    ]
