# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-08 07:15
from __future__ import unicode_literals

import app.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_auto_20170708_1258'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True, verbose_name='이름')),
                ('name_en', models.CharField(blank=True, max_length=64, null=True, verbose_name='이름(EN)')),
                ('intro', models.TextField(blank=True, null=True, verbose_name='소개')),
                ('intro_en', models.TextField(blank=True, null=True, verbose_name='소개(EN)')),
                ('facebook_url', models.URLField(blank=True, null=True, verbose_name='페이스북URL')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to=app.models.profile_upload_path)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='가입일')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='myuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
