# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-09 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20170708_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='experienceitem',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='today',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='todayitem',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
