# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-09 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20170709_1928'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ['display_order']},
        ),
        migrations.AlterModelOptions(
            name='experienceitem',
            options={'ordering': ['display_order']},
        ),
        migrations.AlterModelOptions(
            name='today',
            options={'ordering': ['display_order']},
        ),
        migrations.AlterModelOptions(
            name='todayitem',
            options={'ordering': ['display_order']},
        ),
        migrations.AddField(
            model_name='experience',
            name='company_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='회사(EN)'),
        ),
        migrations.AddField(
            model_name='experienceitem',
            name='key_str_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Key(EN)'),
        ),
        migrations.AddField(
            model_name='experienceitem',
            name='value_str_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Value(EN)'),
        ),
        migrations.AddField(
            model_name='todayitem',
            name='key_str_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Key(EN)'),
        ),
        migrations.AddField(
            model_name='todayitem',
            name='value_str_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Value(EN)'),
        ),
    ]
