# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20170709_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='position',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='직책'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='position_en',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='직책(EN)'),
        ),
    ]
