# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20170711_0232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='종료일'),
        ),
    ]
