# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20170712_0133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='type',
            field=models.CharField(choices=[('professional', 'Professional'), ('private', 'Private'), ('other', 'Education & Other')], max_length=20, verbose_name='타입'),
        ),
    ]
