# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-15 04:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20170712_0136'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experienceitem',
            options={'ordering': ['display_order', 'parent']},
        ),
        migrations.AddField(
            model_name='experience',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='활성화여부'),
        ),
        migrations.AddField(
            model_name='experienceitem',
            name='experience',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='app.Experience'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experienceitem',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='활성화여부'),
        ),
        migrations.AddField(
            model_name='todayitem',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='활성화여부'),
        ),
    ]
