# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-23 07:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20170715_1345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experienceitem',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='experienceitem',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='user',
        ),
        migrations.RemoveField(
            model_name='todayitem',
            name='today',
        ),
        migrations.DeleteModel(
            name='Experience',
        ),
        migrations.DeleteModel(
            name='ExperienceItem',
        ),
        migrations.DeleteModel(
            name='MyUser',
        ),
        migrations.DeleteModel(
            name='Today',
        ),
        migrations.DeleteModel(
            name='TodayItem',
        ),
    ]
